Fixed based on the review by @kylemanna. Thanks.

diff --git a/bin/ovpn_getclient b/bin/ovpn_getclient
--- a/bin/ovpn_getclient
+++ b/bin/ovpn_getclient
@@ -25,7 +25,7 @@ cn="$1"
 parm="$2"
 
 if [ ! -f "$EASYRSA_PKI/private/${cn}.key" ]; then
-    >&2 "Unable to find \"${cn}\", please try again or generate the key first" 1>&2
+    echo "Unable to find \"${cn}\", please try again or generate the key first" >&2
     exit 1
 fi
 
@@ -39,8 +39,8 @@ remote-cert-tls server
 
 remote $OVPN_CN $OVPN_PORT $OVPN_PROTO
 "
-if [ "$mode" == "combined" ]; then
-    echo "
+    if [ "$mode" == "combined" ]; then
+        echo "
 <key>
 $(cat $EASYRSA_PKI/private/${cn}.key)
 </key>
@@ -58,23 +58,23 @@ $(cat $EASYRSA_PKI/ta.key)
 </tls-auth>
 key-direction 1
 "
-else
-    echo "
+    elif [ "$mode" == "separated" ]; then
+        echo "
 key ${cn}.key
 ca ca.crt
 cert ${cn}.crt
 dh dh.pem
 tls-auth ta.key 1
 "
-fi
+    fi
 
-if [ "$OVPN_DEFROUTE" != "0" ];then
-    echo "redirect-gateway def1"
-fi
+    if [ "$OVPN_DEFROUTE" != "0" ];then
+        echo "redirect-gateway def1"
+    fi
 
-if [ -n "$OVPN_MTU" ]; then
-    echo "tun-mtu $OVPN_MTU"
-fi
+    if [ -n "$OVPN_MTU" ]; then
+        echo "tun-mtu $OVPN_MTU"
+    fi
 }
 
 dir="$OPENVPN/clients/$cn"
@@ -88,16 +88,16 @@ case "$parm" in
         cp "$EASYRSA_PKI/dh.pem" "$dir/dh.pem"
         cp "$EASYRSA_PKI/ta.key" "$dir/ta.key"
         ;;
-    "combined")
+    "" | "combined")
         get_client_config "combined"
         ;;
     "combined-save")
         get_client_config "combined" > "$dir/${cn}-combined.ovpn"
         ;;
     *)
-        >&2 echo "This script can produce the client configuration in to formats."
-        >&2 echo "    1. combined: All needed configuration and cryptographic material is in one file (Use \"combined-save\" to write the configuration file in the same path as the separated parameter does)."
-        >&2 echo "    2. separated: Separated files."
-        >&2 echo "Please specific one of those options as second parameter."
+        echo "This script can produce the client configuration in to formats:" >&2
+        echo "    1. combined (default): All needed configuration and cryptographic material is in one file (Use \"combined-save\" to write the configuration file in the same path as the separated parameter does)." >&2
+        echo "    2. separated: Separated files." >&2
+        echo "Please specific one of those options as second parameter." >&2
         ;;
 esac
